---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany # ReadOnlyMany not supported
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  labels:
    run: redmine
  name: redmine-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      run: redmine
  template:
    metadata:
      labels:
        run: redmine
    spec:
      volumes:
      - name: www
        persistentVolumeClaim:
          claimName: test-pvc
      containers:
      - image: redmine
        name: redmine
        volumeMounts:
        - name: www
          mountPath: /usr/share/redmine/html
        ports:
          - name: http
            containerPort: 80 
            
---
apiVersion: v1
kind: Service
metadata:
  name: redmine-service
spec:
  selector:
    run: redmine
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redmine-ingress
spec:
  rules:
  - host: redmine.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: redmine-service
            port: 
              number: 80 
              

