---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany # ReadOnlyMany not supported
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  labels:
    run: redmine
  name: redmine-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      run: redmine
  template:
    metadata:
      labels:
        run: redmine
    spec:
      volumes:
      - name: www
        persistentVolumeClaim:
          claimName: test-pvc
      containers:
      - image: redmine
        name: redmine
        volumeMounts:
        - name: www
          mountPath: /usr/src/redmine/files
        ports:
          - name: http
            containerPort: 3000
            
---
apiVersion: v1
kind: Service
metadata:
  name: redmine-service
spec:
  selector:
    run: redmine
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  labels:
    run: scm-manager
  name: scm-manager-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      run: scm-manager
  template:
    metadata:
      labels:
        run: scm-manager
    spec:
      volumes:
      - name: www
        persistentVolumeClaim:
          claimName: test-pvc
      containers:
      - image: sdorra/scm-manager
        name: scm-manager
        volumeMounts:
        - name: www
          mountPath: /var/lib/scm
        ports:
          - name: http
            containerPort: 8080 
       
---
apiVersion: v1
kind: Service
metadata:
  name: scm-manager-service
spec:
  selector:
    run: scm-manager
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redmine-ingress
spec:
  rules:
  - host: redmine.local
    http:
      paths:
      - path: /
        pathType: Prefix 
        backend:
          service:
            name: redmine-service
            port: 
              number: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scm-manager-ingress
spec:
  rules:
  - host: scm-manager.local
    http:
      paths:
      - path: /
        pathType: Prefix 
        backend:
          service:
            name: scm-manager-service
            port: 
              number: 8080
              

