---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany # ReadOnlyMany not supported
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  labels:
    run: sdorra/scm-manager
  name: sdorra/scm-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      run: sdorra/scm-manager
  template:
    metadata:
      labels:
        run: sdorra/scm-manager
    spec:
      volumes:
      - name: www
        persistentVolumeClaim:
          claimName: test-pvc
      containers:
      - image: sdorra/scm-manager
        name: sdorra/scm-manager
        volumeMounts:
        - name: www
          mountPath: /usr/share/sdorra/scm-manager/html
        ports:
          - name: http
            containerPort: 80 
